# Лабораторная работа №4 "Классификация в многомерном пространстве"

In [3]:
import numpy as np
import matplotlib.pyplot as plt
from abc import ABC, abstractmethod
np.random.seed(42)

## Постановка задачи

Имеем обучающую выборку в виде векторов многомерного пространства (размерность: 4 - 6). Выборка разделена на 3 непересекающиеся классы. 

Необходимо, на основе обучающей выборки, провести классификацию тестовой выборки тремя разными способами. Способы будут описаны ниже.

## Создание выборок

In [61]:
class ABC_Sample(ABC):
  
    @abstractmethod
    def generate(self, n):
        """
        сгенерировать множество из n точек класса
        """
        pass

In [62]:
class Uniform_Sample(ABC_Sample):
    def __init__(self, limits_list):
        """
        limits_list is list with limits for each dimension
        limits_list = [[min_1, max_1], ..., [min_n, max_n]]
        """
        self.limits_list = np.array(limits_list)
        self.dim = len(limits_list)
    def generate(self,n):
        return np.random.random((n,self.dim)) * \
            (self.limits_list[:,1] - self.limits_list[:,0]) + self.limits_list[:,0]

In [66]:
class Normal_sample(ABC_Sample):
    def __init__ (self, params_list):
        """
        limits_list is list with mean and Standard deviation for each dimension
        limits_list = [[mu_1, sigma_1], ..., [mu_n, sigma_n]]
        """
        self.params_list = np.array(params_list)
        self.dim = len(params_list)
    def generate(self, n):
        return np.hstack([np.random.normal(item[0], item[1],size =  (n,1)) 
                         for item in self.params_list])

In [ ]:
class Model (ABC):
    def fit(X,y):
        """
        fit model. 
        X - dots. shape (N, dim)
        y - labels. shape (N,)
        """
        pass


In [6]:
a = np.arange(10)

In [7]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
a = a.reshape(2,5)
a

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [19]:
a * np.arange(5)

array([[ 0,  1,  4,  9, 16],
       [ 0,  6, 14, 24, 36]])

In [59]:
np.hstack((a, np.arange(2).reshape(-1,1)))

array([[0, 1, 2, 3, 4, 0],
       [5, 6, 7, 8, 9, 1]])

TypeError: 'NoneType' object cannot be interpreted as an integer